# Generated by Django 3.0.7 on 2020-06-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenomena', '0002_auto_20200624_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='event_location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='date',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
